### ISSUE TITLE
字体颜色修改

### ISSUE THREAD

**Issue by Donaghys** [zcswdt/Color_OCR_image_generator#2]
您好，~请教下，我只想生成击打的增值税发票的那种蓝色的字体，我应该如何修改呢？

**Comment by zcswdt** [comment]
1. 修改这个地方的rgb通道值为(0,0,25)。
https://github.com/zcswdt/Color_OCR_image_generator/blob/e9c62c1a8f887fe4342c6c2c3ce5ab2f8b545f00/OCR_image_generator.py#L240
2.并使用命令行参数 python OCR_image_generator.py --customize_color来产生图片，改成其他的颜色同理。

**Comment by Donaghys** [comment]
> 1. 修改这个地方的rgb通道值为(0,0,25)。
>    https://github.com/zcswdt/Color_OCR_image_generator/blob/e9c62c1a8f887fe4342c6c2c3ce5ab2f8b545f00/OCR_image_generator.py#L240
>    
>    2.并使用命令行参数 python OCR_image_generator.py --customize_color来产生图片，改成其他的颜色同理。

感谢您的解答。
