### ISSUE TITLE
请指教识别的字符类别

### ISSUE THREAD

**Issue by Donaghys** [zcswdt/Color_OCR_image_generator#3]
识别的字符类别以文件中的语料库出现的字为准？还是以dict5990.txt中的文字为准？有点分不开~~~~，

**Comment by zcswdt** [comment]
以dict5990.txt为准，你可以在文件夹/tools/下执行sentence_filter.py，来对你的语料执行过滤，将你语料库中不在字典中的字符过滤掉，然后在使用该语料来生成文字。

**Comment by Donaghys** [comment]
谢谢~
