### ISSUE TITLE
您好，请教您一个问题

### ISSUE THREAD

**Issue by Donaghys** [zcswdt/Color_OCR_image_generator#6]
感谢您在CRNN_Chinese_Characters_Rec下所所做的图像padding的工作，请问输入图像padding到相同尺寸后的对应每张图的label应该怎么处理呢？

**Comment by zcswdt** [comment]
> 感谢您在CRNN_Chinese_Characters_Rec下所所做的图像padding的工作，请问输入图像padding到相同尺寸后的对应每张图的label应该怎么处理呢？

图像的label不变啊，还是原来的label。
pad前，
![image](https://user-images.githubusercontent.com/43515926/100731614-92aa1400-3406-11eb-86d6-c3afed611af7.png)
pad后
![image](https://user-images.githubusercontent.com/43515926/100731577-87ef7f00-3406-11eb-89be-be208638e510.png)

**Comment by Donaghys** [comment]
哦哦哦 label不动是吧？哦哦 我知道了感谢，感谢，~~
