### ISSUE TITLE
您好，又来请教您问题了~

### ISSUE THREAD

**Issue by Donaghys** [zcswdt/Color_OCR_image_generator#7]
您好，https://github.com/Sierkinhane/CRNN_Chinese_Characters_Rec请问您使用这个项目训练自己的数据，有没有遇到GPU训练loss不下降的问题？训练时原始 预测使用 pred=model（inp）.cpu()。使用CPU做预测，bs设置为1024，在我这边服务器速度大约500张/s，因为我的资源配置充足，所以我改用GPU预测，删除了.cpu()这个命令，达到了3000张/s，（仅仅做了这一个修改，）奇怪的事情发生了，loss就无法正常下降了，正常如果使用CPU预测，在项目作者提供的预训练模型下，loss正常收敛下降，最终loss能在0.001左右，90%多的精度，使用GPU后，loss只能收敛到0.6左右,而且出现了Nan，学习率和loss我都试着修改过，但是loss始终下不去，而且我在想是不是我自己的数据集的问题，我又使用项目作者提供的数据集，使用GPU做训练预测，loss依然不能下降，我不知道问题出在了哪里，一直困惑我好久了，不知道您有没有遇到过类型的问题，能不能给我一点建议？

**Comment by zcswdt** [comment]
> 您好，[https://github.com/Sierkinhane/CRNN_Chinese_Characters_Rec请问您使用这个项目训练自己的数据，有没有遇到GPU训练loss不下降的问题？训练时原始](https://github.com/Sierkinhane/CRNN_Chinese_Characters_Rec%E8%AF%B7%E9%97%AE%E6%82%A8%E4%BD%BF%E7%94%A8%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E8%AE%AD%E7%BB%83%E8%87%AA%E5%B7%B1%E7%9A%84%E6%95%B0%E6%8D%AE%EF%BC%8C%E6%9C%89%E6%B2%A1%E6%9C%89%E9%81%87%E5%88%B0GPU%E8%AE%AD%E7%BB%83loss%E4%B8%8D%E4%B8%8B%E9%99%8D%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%9F%E8%AE%AD%E7%BB%83%E6%97%B6%E5%8E%9F%E5%A7%8B) 预测使用 pred=model（inp）.cpu()。使用CPU做预测，bs设置为1024，在我这边服务器速度大约500张/s，因为我的资源配置充足，所以我改用GPU预测，删除了.cpu()这个命令，达到了3000张/s，（仅仅做了这一个修改，）奇怪的事情发生了，loss就无法正常下降了，正常如果使用CPU预测，在项目作者提供的预训练模型下，loss正常收敛下降，最终loss能在0.001左右，90%多的精度，使用GPU后，loss只能收敛到0.6左右,而且出现了Nan，学习率和loss我都试着修改过，但是loss始终下不去，而且我在想是不是我自己的数据集的问题，我又使用项目作者提供的数据集，使用GPU做训练预测，loss依然不能下降，我不知道问题出在了哪里，一直困惑我好久了，不知道您有没有遇到过类型的问题，能不能给我一点建议？

我没遇到你这种情况，或许你应该请教一下原作者，
