### ISSUE TITLE
您好，请问您一个代码细节问题

### ISSUE THREAD

**Issue by Donaghys** [zcswdt/Color_OCR_image_generator#8]
您好，我想在您的代码基础上修改字符选择的方式，将随机字符选择变为语料随机行选取，但是我注意到：
在生成的函数里您对于 f_w 和w的判断，最好的选择的字符宽度比背景宽度小，但是如果碰到字符宽度大于背景图片的时候，使用pass 直接跳过，这样就有可能导致在判读字符长度如果大于图片宽度陷入一个死循环，但是我目前确实遇到了这个情况，我想处理掉这个情况，我应该怎么解决呢？

**Comment by zcswdt** [comment]
> ，将随机字符选择变为语料随机行选取，但是我注意到：
> 在生成的函数里您对于 f_w 和w的判断，

请贴一下f_w的位置和pass跳过的地方吧

**Comment by Donaghys** [comment]
def get_horizontal_text_picture(image_file,color_lib,char_lines,fonts_list,font_unsupport_chars,cf):
    retry = 0
    img = Image.open(image_file)
    #print('image_file',image_file)
    if img.mode != 'RGB':
        img = img.convert('RGB')
    w, h = img.size
    #print('w',w)
    #print('h',h)
    

    #随机加入空格
    rd = random.random()
    #print('rd',rd)
    if rd < 0.3: 
 
        while True:              
            width = 0
            height = 0
            chars_size = []
            y_offset = 10 ** 5    
            
            #随机获得不定长的文字
            chars = get_chars(char_lines)

            #随机选择一种字体
            font_path = random.choice(fonts_list)
            font_size = random.randint(cf.font_min_size,cf.font_max_size)
            
            #获得字体，及其大小
            font = ImageFont.truetype(font_path, font_size) 
            #不支持的字体文字，按照字体路径在该字典里索引即可        
            unsupport_chars = font_unsupport_chars[font_path]   
                                      
            for c in chars:
                size = font.getsize(c)
                chars_size.append(size)
                width += size[0]
                
                # set max char height as word height
                if size[1] > height:
                    height = size[1]
    
                # Min chars y offset as word y offset
                # Assume only y offset
                c_offset = font.getoffset(c)
                if c_offset[1] < y_offset:
                    y_offset = c_offset[1]    
                    
            char_space_width = int(height * np.random.uniform(-0.1, 0.3))
    
            width += (char_space_width * (len(chars) - 1))            
            
            f_w, f_h = width,height
            
            if f_w < w:
                # 完美分割时应该取的
                x1 = random.randint(0, w - f_w)
                y1 = random.randint(0, h - f_h)
                x2 = x1 + f_w
                y2 = y1 + f_h
                
                #加一点偏移
                if cf.random_offset:
                    print('cf.random_offset',cf.random_offset)
                    # 随机加一点偏移，且随机偏移的概率占30%                
                    rd = random.random()                    
                    if rd < 0.3:  # 设定偏移的概率
                        crop_y1 = y1 - random.random() / 5 * f_h
                        crop_x1 = x1 - random.random() / 2 * f_h
                        crop_y2 = y2 + random.random() / 5 * f_h
                        crop_x2 = x2 + random.random() / 2 * f_h
                        crop_y1 = int(max(0, crop_y1))
                        crop_x1 = int(max(0, crop_x1))
                        crop_y2 = int(min(h, crop_y2))
                        crop_x2 = int(min(w, crop_x2))
                    else:
                        crop_y1 = y1
                        crop_x1 = x1
                        crop_y2 = y2
                        crop_x2 = x2
                else:
                    crop_y1 = y1
                    crop_x1 = x1
                    crop_y2 = y2
                    crop_x2 = x2                
                
                crop_img = img.crop((crop_x1, crop_y1, crop_x2, crop_y2))
                crop_lab = cv2.cvtColor(np.asarray(crop_img), cv2.COLOR_RGB2Lab)
                #print('crop_lab.size',crop_lab.size)
           
                all_in_fonts=word_in_font(chars,unsupport_chars,font_path)
                #print('all_in_fonts',all_in_fonts)
                # kk=np.linalg.norm(np.reshape(np.asarray(crop_lab),(-1,3)).std(axis=0))
                # print('kk',kk)
                if (np.linalg.norm(np.reshape(np.asarray(crop_lab),(-1,3)).std(axis=0))>55 or all_in_fonts) and retry<30:  # 颜色标准差阈值，颜色太丰富就不要了
                    retry = retry+1                               
                    #print('retry',retry)
                    continue
                if not cf.customize_color:
                    best_color = get_bestcolor(color_lib, crop_lab)
                else:    
                    r = random.choice([7,9,11,14,13,15,17,20,22,50,100])
                    g = random.choice([8,10,12,14,21,22,24,23,50,100])
                    b = random.choice([6,8,9,10,11,30,21,34,56,100])
                    best_color = (r,g,b)                
                #print('best_color',best_color)
                break
            else:
                pass



就是着里面的 这个if的判断，  if f_w < w:      我的语料选择上因为字体及语料的原因，f_w 的宽度大于选择的背景的图片的宽度，
函数直接跳到末尾 else的地方，陷入死循环。我现在除了选择一个张宽度及大的背景图外我想不到别的办法

**Comment by zcswdt** [comment]
> w

你可以在pass替换成一种判断，当语料的长度大于图片的长度。1.重新选择语料，直到语料长度小于图片长度。2.重新选择背景图片，直到背景图片大于语料长度。

**Comment by Donaghys** [comment]
好的，我试试，谢谢
