### ISSUE TITLE
请教下您CRNN的不定长训练与识别

### ISSUE THREAD

**Issue by Donaghys** [zcswdt/Color_OCR_image_generator#9]
感谢您贡献的图像padding代码，这是我padding前的图像
![image](https://user-images.githubusercontent.com/49194956/103432853-b9d04d00-4c21-11eb-9fa8-32ce73c470da.png)
这是我padding后的图像，
![image](https://user-images.githubusercontent.com/49194956/103432859-c654a580-4c21-11eb-9ec3-bee4bf9a861b.png)
这样子大概是生成了60W的数据，训练了19个epoch后模型验证集精度为
![image](https://user-images.githubusercontent.com/49194956/103432881-1c294d80-4c22-11eb-825b-fec4b9c192ab.png)
但是在测试场景下精度只有47%
![image](https://user-images.githubusercontent.com/49194956/103432932-12541a00-4c23-11eb-8fa1-deb61b75e283.png)
的识别结果只有：
![image](https://user-images.githubusercontent.com/49194956/103432942-2d268e80-4c23-11eb-8548-bc31e9f360f4.png)
我应该从哪些地方做改进呢？

**Comment by zcswdt** [comment]
> 感谢您贡献的图像padding代码，这是我padding前的图像
> ![image](https://user-images.githubusercontent.com/49194956/103432853-b9d04d00-4c21-11eb-9fa8-32ce73c470da.png)
> 这是我padding后的图像，
> ![image](https://user-images.githubusercontent.com/49194956/103432859-c654a580-4c21-11eb-9ec3-bee4bf9a861b.png)
> 这样子大概是生成了60W的数据，训练了19个epoch后模型验证集精度为
> ![image](https://user-images.githubusercontent.com/49194956/103432881-1c294d80-4c22-11eb-825b-fec4b9c192ab.png)
> 但是在测试场景下精度只有47%
> ![image](https://user-images.githubusercontent.com/49194956/103432932-12541a00-4c23-11eb-8fa1-deb61b75e283.png)
> 的识别结果只有：
> ![image](https://user-images.githubusercontent.com/49194956/103432942-2d268e80-4c23-11eb-8548-bc31e9f360f4.png)
> 我应该从哪些地方做改进呢？

你的字典有多少个字符，测试场景都是什么场景，和你生成图片的场景差异大么？

**Comment by Donaghys** [comment]
字符集通用的被过滤了只有5990个，测试场景来源于真实的击打增值税发票。看起来还有有些差异的，但是感觉精度不至于那么低。

**Comment by Donaghys** [comment]
生成图片方面，请问您有啥建议吗？（除了用真实数据外）我应该加一些什么样子的图像处理操作呢?

**Comment by zcswdt** [comment]
> 字符集通用的被过滤了只有5990个，测试场景来源于真实的击打增值税发票。看起来还有有些差异的，但是感觉精度不至于那么低。

第一，首先从你的字符上来看，5990个字符，你合成60万数据是远远不够的。第二，你应该合成和你测试场景相似的图片，比如增值发票上的字都是绿色或者红色，你就没必要合成其他的颜色，找增值税发票相似的背景进行合成。

**Comment by zcswdt** [comment]
> 生成图片方面，请问您有啥建议吗？（除了用真实数据外）我应该加一些什么样子的图像处理操作呢?



> 应该加一些什么样子的图像处理操作

第一，生产图片方面你要生成和你识别场景相似的图片来做一些比如图像模糊，引入噪音等。第二，查看你的场景，归纳总结你的字体种类，下载相似的字体进行生生图片。第三，建议你生成图片都是不定长的字符。

**Comment by Donaghys** [comment]
好的，谢谢您。~
